### PR TITLE
:racehorse: Replace for loops by Array methods - filter()

### PR DESCRIPTION
**Pull request by nattatorn-dev**
Replace for loops by Array methods - filter(), Your unit tests still working.

### CODE REVIEW

**Review by ardeshireshghi — COMMENTED** [review]
It looks much better. Does it affect the speed. As usually map and filter are relatively more expensive than normal loops. But looks for functional style than mine :)

I will do a performance test and will merge in

**Comment by nattatorn-dev** [comment]
Thanks for your quick reply, I will do a performance comparison of for loops and filter too.

**Comment by nattatorn-dev** [comment]
@ardeshireshghi I already have some simple performance tests.

screen shot 2017-10-15 11 06 55 pm

- node version v7.10.0
- benchmark v2.1.2

normal loops  is faster than filter() or for in.
Thank for the guidance.

**Comment by ardeshireshghi** [comment]
Thanks for doing the performance test. Is it okay to close this then?

**Pull request closed without merging**
